import type { Metadata } from "next";
import { BrandedFooter, ImageHero } from "../components/site";
import { PageSeo } from "../components/page-seo";

const description = "How OIA Group collects, uses, discloses and protects personal information.";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description,
  alternates: { canonical: "/privacy-policy/" },
  openGraph: { type: "website", title: "Privacy Policy | OIA Group", description, url: "/privacy-policy/", images: [{ url: "/figma/privacy/hero.png", alt: "Curved contemporary building facade" }] },
};

const BulletList = ({ children }: { children: React.ReactNode }) => <ul>{children}</ul>;

export default function PrivacyPolicy() {
  return <div className="privacy-page">
    <PageSeo name="Privacy Policy" description={description} path="/privacy-policy/" breadcrumbs={[{ name: "Home", path: "/" }, { name: "Privacy Policy", path: "/privacy-policy/" }]} />
    <ImageHero className="privacy-hero" image="/figma/privacy/hero.png" alt="Curved contemporary building facade" title="Privacy Policy" />

    <article className="privacy-content">
      <section><h2>1. Overview</h2><p>Oriental Investment Australia Group Pty Ltd and its related entities (OIA Group, we, us or our) are committed to protecting your privacy and handling your personal information in accordance with the Privacy Act 1988 (Cth) and the Australian Privacy Principles (APPs).</p><p>This Privacy Policy explains how we collect, use, disclose and manage personal information in connection with our business, including property development, sales, leasing and investment activities, and through our website.</p></section>

      <section><h2>2. Scope of this Policy</h2><p>This Policy applies to personal information collected:</p><BulletList><li>through our website and project websites;</li><li>when you make enquiries or register interest in developments;</li><li>during sales, leasing or investment processes;</li><li>through agents, consultants and third parties; and</li><li>via our interactions with you, including marketing and events.</li></BulletList><p>Where multiple related entities are involved in a development, your personal information may be collected and used jointly by those entities.</p></section>

      <section><h2>3. What is Personal Information</h2><p>Personal information means information or an opinion about an identified individual or an individual who is reasonably identifiable.</p><p>The types of personal information we may collect include, but are not limited to:</p><h3>a. Contact and Identification Information</h3><BulletList><li>name, address, email address and phone number;</li><li>date of birth;</li><li>identification documents (e.g. passport, driver licence or national ID); and</li><li>residency or visa status.</li></BulletList><h3>b. Transaction and Property-Related Information</h3><BulletList><li>property enquiries, preferences and registration details;</li><li>contract details, account information and correspondence; and</li><li>defect notifications and customer service records.</li></BulletList><h3>c. Financial Information</h3><BulletList><li>financial and banking information; and</li><li>other relevant financial details (where permitted by law).</li></BulletList><h3>d. Technical and Usage Data</h3><BulletList><li>IP address and device information;</li><li>cookies and browsing data; and</li><li>location data (where enabled).</li></BulletList><h3>e. Sensitive Information (where applicable)</h3><BulletList><li>biometric information (e.g. facial recognition or voice data);</li><li>disability or health-related information (where provided); and</li><li>tax file number or withholding information (where required).</li></BulletList><h3>f. Audio-Visual Information</h3><BulletList><li>CCTV footage; and</li><li>video or call recordings, including images, videos and voice recordings.</li></BulletList><h3>g. Business and Professional Information</h3><BulletList><li>consultants, contractors and suppliers’ contact details and references.</li></BulletList><p>We will only collect Sensitive Information with your consent or where otherwise permitted or required by law.</p></section>

      <section><h2>4. How We Collect Personal Information</h2><p>We collect personal information in a number of ways, including but not limited to:</p><BulletList><li>directly from you (for example, when you make enquiries, complete forms, enter into contracts or communicate with us);</li><li>when you register your interest in a development, subscribe to updates, attend inspections, events or display suites;</li><li>through real estate agents, brokers, sales representatives, property managers and consultants engaged in connection with our developments;</li><li>via our websites, digital platforms, cookies and analytics tools;</li><li>through your interactions with our marketing materials, including online advertisements, social media platforms and email communications;</li><li>from publicly available sources and registers; and</li><li>from third parties involved in transactions or developments, including financial institutions, professional advisers and service providers.</li></BulletList><p>We may also collect personal information automatically when you interact with our website or digital platforms, including information about your device, browsing activity and usage patterns.</p><p>Where reasonable and practicable, we collect personal information directly from you. Where we collect information from third parties, we will take reasonable steps to ensure that you are aware of the collection.</p><p>Where you provide us with personal information about someone else you must have their consent to provide their personal information to us based on this Privacy Policy.</p></section>

      <section><h2>5. Why We Collect Personal Information</h2><p>We collect and use personal information for purposes including but not limited to:</p><BulletList><li>responding to enquiries and providing information about our developments, projects and services;</li><li>registering and managing your interest in developments, including pre-sales, reservations and expressions of interest;</li><li>managing transactions, including contract preparation, sales, settlement and post-settlement services;</li><li>administering leasing, property management and ongoing customer relationships;</li><li>communicating with you, including providing updates, marketing communications, event invitations and project announcements;</li><li>conducting marketing, analytics and market research, and improving our services, developments and website functionality;</li><li>verifying your identity and carrying out due diligence, including for legal, regulatory and compliance purposes (such as anti-money laundering requirements where applicable);</li><li>engaging with agents, brokers, consultants and other third parties in connection with developments and transactions;</li><li>protecting our legal rights and interests, including enforcing agreements and managing disputes; and</li><li>complying with our legal and regulatory obligations.</li></BulletList><p>We may also use your personal information for purposes that are related to, or reasonably expected in connection with, the purposes described above.</p></section>

      <section><h2>6. Disclosure of Personal Information</h2><p>We may disclose your personal information to third parties for the purposes described in this Privacy Policy, including but not limited to:</p><BulletList><li>related entities within the OIA Group, including entities involved in the development, marketing, sale or management of our projects;</li><li>real estate agents, brokers, sales representatives, property managers and consultants engaged in connection with our developments;</li><li>contractors and service providers who assist us in operating our business, including IT service providers, cloud hosting providers, marketing and analytics providers, and customer relationship management (CRM) platforms;</li><li>professional advisers, including lawyers, accountants, auditors and consultants;</li><li>financial institutions, lenders and payment processors in connection with transactions;</li><li>government authorities, regulators or other bodies where required or authorised by law;</li><li>business partners, joint venture participants and investors involved in developments or transactions; and</li><li>any other third parties with your consent or as otherwise permitted by law.</li></BulletList><p>We may also disclose personal information:</p><BulletList><li>where it is reasonably necessary to enforce our legal rights, agreements or policies;</li><li>to prevent, detect or investigate fraud, misconduct or unlawful activity;</li><li>in connection with a sale, merger, restructuring or transfer of all or part of our business or assets; and</li><li>where disclosure is required to comply with legal obligations, court orders or regulatory requirements.</li></BulletList><p>Where personal information is disclosed to third parties, we take reasonable steps to ensure that such parties handle the information in accordance with applicable privacy laws and use it only for the purposes for which it is disclosed. However, you acknowledge that we do not control the privacy practices of third parties and are not responsible for their acts or omissions, except to the extent required by law.</p></section>

      <section><h2>7. Overseas Disclosure</h2><p>Some recipients of personal information may be located outside Australia, including our related entities, service providers, contractors and business partners.</p><p>Where we disclose personal information to overseas recipients, we will take reasonable steps to ensure that the recipient does not breach the Australian Privacy Principles (APPs) in relation to that information. This may include implementing contractual arrangements, data protection measures or relying on other lawful mechanisms to safeguard your personal information.</p><p>By providing your personal information to us, you acknowledge and consent to the disclosure of your personal information to overseas recipients in accordance with this Privacy Policy.</p><p>You also acknowledge that, in some circumstances, overseas recipients may not be subject to privacy laws that are equivalent to those in Australia, and you may not be able to seek redress under Australian privacy laws in relation to acts or omissions of those recipients.</p></section>

      <section><h2>8. Cookies and Online Data</h2><p>We use cookies and similar technologies (such as web beacons, pixels and analytics tools) to collect and process information about your interactions with our website and digital platforms.</p><p>This may include information such as your IP address, device type, browser type, pages visited, time spent on pages, referring URLs and general location data.</p><p>We use this information to:</p><BulletList><li>operate, maintain and improve our website and services;</li><li>analyse user behaviour, trends and website performance;</li><li>personalise your experience and tailor content;</li><li>support our marketing and advertising activities, including delivering relevant advertisements; and</li><li>measure the effectiveness of our marketing campaigns.</li></BulletList><p>We may use third-party service providers, such as analytics and advertising partners, who may also collect and process this information in accordance with their own privacy policies.</p><p>You can control or disable cookies through your browser settings. However, if you choose to do so, some parts of our website may not function properly or may be less accessible.</p></section>

      <section><h2>9. Security of Personal Information</h2><p>We take reasonable technical, administrative and organisational measures to protect personal information from misuse, interference and loss, and from unauthorised access, modification or disclosure.</p><p>These measures may include secure systems, access controls, encryption (where appropriate), and procedures designed to safeguard personal information in both electronic and physical form.</p><p>We may store personal information in electronic systems (including cloud-based platforms) and in physical records. Access to personal information is limited to personnel and service providers who require access for legitimate business purposes.</p><p>While we take reasonable steps to protect personal information, no method of transmission over the internet or method of electronic storage is completely secure. Accordingly, we do not guarantee the absolute security of personal information.</p><p>To the extent permitted by law, we are not liable for any unauthorised access to or disclosure of personal information beyond our reasonable control.</p></section>

      <section><h2>10. Access, Correction and Rights</h2><p>You have certain rights under the Privacy Act 1988 (Cth) in relation to the personal information we hold about you.</p><p>Subject to applicable laws, you may contact us to:</p><BulletList><li>request access to the personal information we hold about you;</li><li>request correction of your personal information if it is inaccurate, incomplete or out of date;</li><li>request that we delete or de-identify your personal information where it is no longer required for the purposes for which it was collected (subject to legal and regulatory requirements);</li><li>object to or request restriction of the processing of your personal information in certain circumstances; and</li><li>withdraw your consent where we rely on consent to process your personal information.</li></BulletList><p>We will respond to your request within a reasonable time. In some circumstances, we may not be able to comply with your request (for example, where it would be unlawful or would impact the rights of others). If this occurs, we will notify you and provide reasons where required.</p><p>Where applicable, we may require you to verify your identity before processing your request.</p><p>If you wish to exercise any of your rights, or make a complaint about how we handle your personal information, please contact us using the details set out in this Policy.</p></section>

      <section><h2>11. Marketing Communications</h2><p>We may use your personal information to send you marketing communications about our developments, projects, services, promotions and events, where permitted by law, including the Spam Act 2003 (Cth).</p><p>These communications may be sent via email, SMS, telephone or other electronic means.</p><p>We may also use your personal information to personalise marketing content and to provide you with information that may be of interest to you based on your interactions with us, including your property preferences and enquiries.</p><p>In some cases, we may engage third-party service providers or platforms (such as marketing or advertising providers) to assist in delivering these communications.</p><p>You may opt out of receiving marketing communications at any time by:</p><BulletList><li>using the unsubscribe function included in our communications;</li><li>contacting us directly using the contact details in this Policy; or</li><li>following any other opt-out instructions provided.</li></BulletList><p>We will take reasonable steps to process your opt-out request promptly.</p></section>

      <section><h2>12. Retention of Information</h2><p>We retain personal information only for as long as necessary for:</p><BulletList><li>the purposes for which it was collected;</li><li>any related or reasonably expected purposes;</li><li>our legitimate business needs; and</li><li>compliance with legal, regulatory, accounting or reporting obligations.</li></BulletList><p>The period for which we retain personal information will depend on a number of factors, including the nature and sensitivity of the information, the purpose for which it was collected, and any applicable legal requirements.</p><p>When personal information is no longer required, we will take reasonable steps to destroy or de-identify the information, unless we are required or permitted by law to retain it.</p></section>

      <section><h2>13. Third-Party Websites</h2><p>Our website may contain links to third-party websites, platforms or services that are not operated or controlled by us.</p><p>We do not control, endorse or make any representations about the privacy practices or content of those third-party websites.</p><p>Any personal information you provide to third-party websites will be governed by their own privacy policies and terms. We recommend that you review those policies before providing any personal information.</p><p>To the extent permitted by law, we are not responsible or liable for the privacy practices, content or security of any third-party websites or services. Your use of such websites is at your own risk.</p></section>

      <section><h2>14. Complaints</h2><p>If you believe we have breached applicable privacy laws, you may contact us. We will investigate and respond within a reasonable timeframe. You may also contact the Office of the Australian Information Commissioner (OAIC).</p></section>

      <section><h2>15. Changes to this Policy</h2><p>We may update this Privacy Policy from time to time. The latest version will be published on our website.</p></section>

      <section><h2>16. Contact Us</h2><p>If you have any questions about this Privacy Policy or your personal information, please contact: OIA Group | <a href="mailto:info@oiagroup.com.au">info@oiagroup.com.au</a></p></section>
    </article>
    <BrandedFooter />
  </div>;
}
